export const exerciseList = [
    'Walking',
    'Jogging',
    'Cardiovascular Fitness',
    'Strength Training',
    'Swimming',
    'Stretching',
    'Cycling',
    'Aerobics',
    'Dance',
    'Lunges',
    'Circuit Training',
    'Hiking',
    'Burpees',
    'Interval Training',
    'Jump Rope',
    'Jumping Jack',
    'Basketball',
    'Elliptical Trainer',
    'Biceps Curl',
    'Balance Exercise',
    'Bent-over Row',
    'Boot Camp',
    'Calisthenics'
]