export const foodsBarcode = [

    {
        Barcode: 4803925130328,
        Calcium: 0,
        Calories: 80,
        Category: "",
        Chloride: 0,
        DietaryFiber: 0,
        Flouride: 0,
        Folate: 0,
        Iodine: 0,
        Iron: 0,
        Magnesium: 0,
        Name: "Mountain Dew",
        Niacin: 0,
        Phosphorus: 0,
        Potassium: 0,
        Protein: 0,
        Riboflavin: 0,
        Selenium: 0,
        Sodium: 15,
        Thiamin: 0,
        Vitamin_A: 0,
        Vitamin_B12: 0,
        Vitamin_B6: 0,
        Vitamin_C: 0,
        Vitamin_D: 0,
        Vitamin_E: 0,
        Vitamin_K: 0,
        Zinc: 0,
        amount: 0,
        quantity: 0,
    }
]